from solver.jakobsens import subSolver

# c = 'UWRGT UOCUJ DTQUK UCETQ UUQXG TRNCV HQTOH KIJVK PIICO GUGTK GURWD NKUJG FDAPK PVGPF QVJGU GTKGU YCUET GCVGF DAOCU CJKTQ UCMWT CKYJQ JCUFK TGEVG FGXGT AICOG KPVJG UGTKG UVJGU GTKGU KUMPQ YPHQT KVUWP KSWGI COGRN CAQDL GEVKX GYJKE JFKHH GTUHT QOVJC VQHVT CFKVK QPCNH KIJVG TUKPV JCVVJ GCKOK UVQKP ETGCU GFCOC IGEQW PVGTU CPFMP QEMQR RQPGP VUQHH VJGUV CIGKP UVGCF QHFGR NGVKP INKHG DCTUV JGUGT KGURT KOCTK NAHGC VWTGU EJCTC EVGTU HTQOX CTKQW UPKPV GPFQH TCPEJ KUGUK PENWF KPIUW RGTOC TKQFQ PMGAM QPIVJ GNGIG PFQHB GNFCO GVTQK FAQUJ KMKTD AUVCT HQZCP FRQMG OQPCU YGNNC UVJKT FRCTV AHTCP EJKUG UNKMG UQPKE VJGJG FIGJQ IUVTG GVHKI JVGTC PFHKP CNHCP VCUAV JGQTK IKPCN UWRGT UOCUJ DTQUJ CFQPN ARNCA CDNGE JCTCE VGTUY KVJVJ GTQUV GTEQW PVTKU KPIHQ TGCEJ UWEEG UUKXG ICOGC PFNCV GTKPE NWFKP IVJKT FRCTV AEJCT CEVGT UYKVJ WNVKO CVGEQ PVCKP KPIGX GTAEJ CTCEV GTRNC ACDNG KPVJG RTGXK QWUIC OGUKP OGNGG DTCYN CPFWN VKOCV GUQOG EJCTC EVGTU CTGCD NGVQV TCPUH QTOKP VQFKH HGTGP VHQTO UVJCV JCXGF KHHGT GPVUV ANGUQ HRNCA CPFUG VUQHO QXGUG XGTAI COGKP VJGUG TKGUJ CUDGG PYGNN TGEGK XGFDA ETKVK EUYKV JOWNV KRNGK PUVCN NOGPV UDGKP INKUV GFCOQ PIVJG ITGCV GUVXK FGQIC OGUQH CNNVK OGOWE JRTCK UGJCU DGGPI KXGPV QVJGK TOWNV KRNCA GTHGC VWTGU URCYP KPICN CTIGE QORGV KVKXG EQOOW PKVAV JCVJC UDGGP HGCVW TGFKP UGXGT CNICO KPIVQ WTPCO GPVUR TGTGN GCUGU ETGGP UJQVQ HWNVK OCVGH GCVWT KPIIC PQPFQ THNKP MOCTK QCPFO GICOC PDCVV NGQPV JGITG CVRNC VGCWV QYGTU VCIGD CUGFQ PVJGN QECVK QPHTQ OVJGN GIGPF QHBGN FCDTG CVJQH VJGYK NFICO GRNCA KPVJG UWRGT UOCUJ DTQUU GTKGU FKHHG TUHTQ OOCPA HKIJV KPIIC OGUKP UVGCF QHYKP PKPID AFGRN GVKPI CPQRR QPGPV UNKHG DCTRN CAGTU UGGMV QNCWP EJVJG KTQRR QPGPV UQHHV JGUVC IGCPF QWVQH DQWPF UEJCT CEVGT UJCXG CFCOC IGVQV CNYJK EJTKU GUCUV JGAVC MGFCO CIGTG RTGUG PVGFD ACRGT EGPVC IGXCN WGVJC VOGCU WTGUW RVQCU CEJCT CEVGT URGTE GPVCI GTKUG UVJGA UWHHG TUVTQ PIGTM PQEMD CEMHT QOGPG OACVV CEMUV QMPQE MQWVC PQRRQ PGPVV JGRNC AGTOW UVMPQ EMVJC VEJCT CEVGT QWVUK FGVJG UVCIG UDQWP FCTKG UKPCP AFKTG EVKQP YJGPC EJCTC EVGTK UNCWP EJGFQ HHVJG UVCIG VJGEJ CTCEV GTECP CVVGO RVVQT GEQXG TDAWU KPILW ORKPI OQXGU CPFCD KNKVK GUVQT GVWTP VQVJG UVCIG UQOGE JCTCE VGTUJ CXGCP GCUKG TVKOG TGEQX GTKPI QPVQV JGUVC IGVJC PQVJG TUFWG VQVJG KTOQX GUCPF CDKNK VKGUC FFKVK QPCNN AUQOG EJCTC EVGTU XCTAK PYGKI JVYKV JNKIJ VGTEJ CTCEV GTUDG KPIGC UKGTV QNCWP EJVJC PJGCX AEJCT CEVGTU'
# c = c.replace(' ', '')
# solver = Solver(c)
# solver.key = solver.subSolver()
# print(solver.getPlaintext(solver.key))


def main():

    input_file = 

    with open(input_file) as f:
        ciphertext = f.read().strip()

    s = subSolver(ciphertext)

    print(f"ciphertext:\n{ciphertext}")

    print(f"plaintext:\n{s.plaintext()}\n")